# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: bancodados
      POSTGRES_PASSWORD: bancodados
      POSTGRES_DB: bancodados
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"